JesusParales_hackprofile/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'profile/valentinaloreto' => 'profiles#json_response'

  get 'browse', to: 'browse#search', as: :browse  # 1 -renders the search view bar. linked to friends/new

  post 'friends/new', to: 'friends#new'
  post 'friends', to: 'friends#create' #f 3 ----from hidden form
  get '/friends/:id', to: 'friends#show', as: 'friend'

  resources :profiles, only: [:show, :edit, :update], shallow: true do
    resources :hobbies, except: :show
    resources :photos
    resources :certificates, except: :show
  end
end

JesusParales_hackprofile/app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :profile
  has_one_attached :photo_file
end

JesusParales_hackprofile/app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_profile, only: [:index, :new, :create]
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  def index
    @photos = Photo.all
  end

  def show
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = @profile.photos.build(photo_params)
    if @photo.save
      redirect_to profile_photos_path(@profile), notice: 'Photo was successfully created.'
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @photo.update(photo_params)
      redirect_to @photo, notice: 'Your photo was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @profile = @photo.profile.id
    @photo.destroy
    redirect_to profile_photos_path(@profile), notice: 'Photo was successfully destroyed.'
  end

  private

  def set_photo
    @photo = Photo.find(params[:id])
  end

  def set_profile
    @profile = Profile.find(params[:profile_id])
  end

  def photo_params
    params.require(:photo).permit(:description, :photo_file, :profile_id)
  end
end

JesusParales_hackprofile/app/helpers/photos_helper.rb
module PhotosHelper
end

JesusParales_hackprofile/app/views/photos/edit.html.haml
%h1 Editing Photo

= form_with(model: @photo, local: true) do |form|
  - if @photo.errors.any?
    #error_explanation
      %h2
        = pluralize(@photo.errors.count, "error")
        prohibited this profile from being saved:
      %ul
        - @photo.errors.full_messages.each do |message|
          %li= message
  .field.form-group
    = form.label :description
    = form.text_field :description, class: 'form-control'
  .field.form-group
    = form.label :photo_file
    = form.file_field :photo_file, class: 'form-control'
  .actions
    = form.submit class: 'btn btn-info btn-lg btn-block'

.buttons-group
  .btn.btn-info.btn-lg
    = link_to 'Back to index list', profile_photos_path( @photo.profile.id )

JesusParales_hackprofile/app/views/photos/index.html.haml
%p#notice= notice
%h1 Photos
%table.table
  %thead
    %tr
      %th Description
      %th Photo
      %th{colspan: "3"}
  %tbody
    - @photos.each do |photo|
      %tr
        %td= photo.description
        %td.img-thumbnail
          = image_tag(photo.photo_file)
        %td= link_to 'Show', photo_path( photo )
        %td= link_to 'Edit', edit_photo_path( photo )
        %td= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' }
%br/

.row.actions
  .btn.btn-info.btn-lg.btn-block
    = link_to 'New Photo', new_profile_photo_path( @profile )
  .btn.btn-info
    = link_to 'Back to Edit Page', edit_profile_path(@profile)

JesusParales_hackprofile/app/views/photos/new.html.haml
%h1 New Hobby

= form_with(model: [@profile, @photo], local: true) do |form|
  - if @photo.errors.any?
    #error_explanation
      %h2
        = pluralize(@photo.errors.count, "error")
        prohibited this photo from being saved:
      %ul
        - @photo.errors.full_messages.each do |message|
          %li= message
  .field.form-group
    = form.label :description
    = form.text_field :description, class: 'form-control'
  .field.form-group
    = form.label :photo_file
    = form.file_field :photo_file, class: 'form-control'

  .actions
    = form.submit class: 'btn btn-info btn-lg btn-block'

.buttons-group
  .btn.btn-info.btn-lg
    = link_to 'Back to index list', profile_photos_path( @profile )

JesusParales_hackprofile/app/views/photos/show.html.haml
%p#notice= notice

%p
  %strong Description:
  = @photo.description

%p
  = image_tag(@photo.photo_file)



.buttons-group
  .btn.btn-info.btn-lg
    = link_to 'Back to index list', :back