JesusParales_hackprofile/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'profile/valentinaloreto' => 'profiles#json_response'

  get 'browse', to: 'browse#search', as: :browse  # 1 -renders the search view bar. linked to friends/new

  post 'friends/new', to: 'friends#new'
  post 'friends', to: 'friends#create' #f 3 ----from hidden form
  get '/friends/:id', to: 'friends#show', as: 'friend'

  resources :profiles, only: [:show, :edit, :update], shallow: true do
    resources :hobbies, except: :show
    resources :photos
    resources :certificates, except: :show
  end
end

JesusParales_hackprofile/app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :hobbies
  has_many :photos
  has_many :certificates
  has_many :friends

  attr_accessor :json

  def build_json
    @json = {}
    self.attributes.each { |key, value| @json[key] = value }
    @json['email'] = self.user.email

    get_hobbies
    get_certificates

    @json
  end

  def get_hobbies
    @json['hobbies'] = []
    self.hobbies.each do |hobby|
      hobby_hash = hobby.attributes
      hobby_hash['category'] = hobby.category.name
      @json['hobbies'] <<  hobby_hash
    end
  end

  def get_certificates
    @json['certificates'] = []
    self.certificates.each { |certificate| @json['certificates'] << certificate.attributes }
  end

end

JesusParales_hackprofile/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, except: :json_response
  before_action :set_age, except: :json_response
  before_action :set_hobbies, except: :json_response
  before_action :set_photos, except: :json_response
  before_action :set_friends, except: :json_response
  before_action :set_certificates, except: :json_response

  def show
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to @profile, notice: 'Your profile was successfully updated.'
    else
      render :edit
    end
  end

  def json_response
    profile = Profile.first
    json = profile.build_json
    photo = profile.photos.first.photo_file
    json['image'] = url_for(photo)
    render json: json
  end

  private

  def set_profile
    @profile = Profile.find(params[:id])
  end

  def set_hobbies
    @hobbies = @profile.hobbies
  end

  def set_photos
    @photos = @profile.photos
  end

  def set_certificates
    @certificates = @profile.certificates
  end

  def set_friends
    @friends = @profile.friends
  end

  def set_age
    now = Time.now
    b = @profile.birthdate.to_time
    @age = now.year - b.year - ((now.month > b.month || (now.month == b.month && now.day >= b.day)) ? 0 : 1)
  end

  def profile_params
    params.require(:profile).permit(:firstname, :lastname, :username, :bio, :birthdate, :subtitle)
  end

end

JesusParales_hackprofile/app/helpers/profiles_helper.rb
module ProfilesHelper
end

JesusParales_hackprofile/app/views/profiles/edit.html.haml
%h1 Editing Profile

= form_with(model: @profile, local: true) do |form|
  - if @profile.errors.any?
    #error_explanation
      %h2
        = pluralize(@profile.errors.count, "error")
        prohibited this profile from being saved:
      %ul
        - @profile.errors.full_messages.each do |message|
          %li= message

  .field.form-group
    = form.label :firstname
    = form.text_field :firstname, class: 'form-control'
  .field.form-group
    = form.label :lastname
    = form.text_field :lastname, class: 'form-control'
  .field.form-group
    = form.label :subtitle
    = form.text_field :subtitle, class: 'form-control'
  .field.form-group
    = form.label :bio
    = form.text_area :bio, class: 'form-control'
  .field.form-group
    = form.label :username
    = form.text_field :username, class: 'form-control'


  .actions
    = form.submit class: 'btn btn-info btn-lg btn-block'

.buttons-group
  .btn.btn-info.btn-lg
    = link_to 'Back to Profile', @profile
  .btn.btn-danger.btn-lg
    = link_to 'Edit Hobbies', profile_hobbies_path(@profile)
  .btn.btn-success.btn-lg
    = link_to 'Edit Photos', profile_photos_path(@profile)
  .btn.btn-warning.btn-lg
    = link_to 'Edit Certificates', profile_certificates_path(@profile)

JesusParales_hackprofile/app/views/profiles/show.html.haml
.browse-button
  .btn.btn-info
    = link_to 'Browse for friends', browse_path
%p#notice= notice


%header
  %h1
    = @profile.firstname + " " + @profile.lastname
  %h4
    = @profile.subtitle
  %hr
.row
  .col-md-8.bio
    %p
      = @profile.bio
    %p
      %strong Age:
      = @age
    %p
      %strong Email:
      = @profile.user&.email

  .col-md-4.img
    - @photos.each do |photo|
      .img-thumbnail.test
        = image_tag(photo.photo_file)



.row
  %hr
  %h2 Hobbies

.row.is-flex-row
  - @hobbies.each do |h|
    .col-md-4.col-sm-6
      .card
        .card-body
          %h4.card-title
            = h.name
          %h6.card-subtitle.mb-2.text-muted
            = h.category.name
          %p.card-text
            = h.description

.row.mx-auto
  %hr
  %h2 Certificates
  .col-sm-12
    .certificates-card
      %ul.list-group
      - @certificates.each do |certificate|
        %li.list-group-item
          = certificate.name
          = link_to 'View file', certificate.file

.row
  %hr
  %h2 Friends
.row.is-flex-row
  - @friends.each do |f|
    - begin
      - friend = HTTParty.get(f.url)
      - image = friend['image']
    - rescue Errno::ECONNREFUSED
      - image = "https://cdn-geo.dayre.me/NZKwFWXiVnyg3QLAVoB3.jpg"
    .col-md-2.col-sm-6
      .my-thumbnail-card
        .img-thumbnail
          .thumbnails
            = image_tag(image)
        .btn.btn-info.btn-block
          = link_to "#{friend['firstname']} #{friend['lastname']}", friend_path(f)




.row.actions
  %hr
  .btn.btn-info.btn-lg.btn-block
    = link_to 'Edit', edit_profile_path(@profile)