JesusParales_hackprofile/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'profile/valentinaloreto' => 'profiles#json_response'

  get 'browse', to: 'browse#search', as: :browse  # 1 -renders the search view bar. linked to friends/new

  post 'friends/new', to: 'friends#new'
  post 'friends', to: 'friends#create' #f 3 ----from hidden form
  get '/friends/:id', to: 'friends#show', as: 'friend'

  resources :profiles, only: [:show, :edit, :update], shallow: true do
    resources :hobbies, except: :show
    resources :photos
    resources :certificates, except: :show
  end
end

JesusParales_hackprofile/app/models/hobby.rb
class Hobby < ApplicationRecord
  belongs_to :profile
  belongs_to :category

  #enum preference: [:one, :two, :three, :four, :five]
  enum preference: {
    why_not: 1,
    its_ok: 2,
    like_it: 3,
    love_it: 4,
    favorite: 5
  }

end

JesusParales_hackprofile/app/controllers/hobbies_controller.rb
class HobbiesController < ApplicationController
  before_action :set_profile, only: [:index, :new, :create]
  before_action :set_hobby, only: [:show, :edit, :update, :destroy]
  before_action :set_categories, only: [:new, :edit]
  before_action :set_preferences, only: [:new, :edit]

  def index
    @hobbies = Hobby.all.includes(:category)
  end

  def show
  end

  def new
    @hobby = Hobby.new
  end

  def create

    @hobby = @profile.hobbies.build(hobby_params)
    if @hobby.save
      redirect_to profile_hobbies_path, notice: 'Hobbie was successfully created.'
    else
      render :new
    end

  end

  def edit

  end

  def update
    if @hobby.update(hobby_params)
      redirect_to @hobby, notice: 'Your hobby was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @profile = @hobby.profile.id
    @hobby.destroy
    redirect_to profile_hobbies_path(@profile), notice: 'Hobby was successfully destroyed.'
  end

  private

  def set_profile
    @profile = Profile.find(params[:profile_id])
  end

  def set_hobby
    @hobby = Hobby.find(params[:id])
  end

  def set_categories
    @categories = Category.all.collect { |category| [category.name, category.id] }
  end

  def set_preferences
    @preferences = Hobby.preferences.collect { |key, value| [key.humanize, key] }
  end

  def hobby_params
    params.require(:hobby).permit(:name, :description, :preference, :category_id, :profile_id)
  end
end

JesusParales_hackprofile/app/helpers/hobbies_helper.rb
module HobbiesHelper
end

JesusParales_hackprofile/app/views/hobbies/edit.html.haml
%h1 Editing Hobby

= form_with(model: @hobby, local: true) do |form|
  - if @hobby.errors.any?
    #error_explanation
      %h2
        = pluralize(@hobby.errors.count, "error")
        prohibited this profile from being saved:
      %ul
        - @hobby.errors.full_messages.each do |message|
          %li= message
  .field.form-group
    = form.label :name
    = form.text_field :name, class: 'form-control'
  .field.form-group
    = form.label :description
    = form.text_field :description, class: 'form-control'
  .field.form-group
    = form.label :preference
    = form.select :preference, @preferences, include_blank: true
  .field.form-group
    = form.label :category
    = form.select :category_id, @categories, include_blank: true
  .actions
    = form.submit class: 'btn btn-info btn-lg btn-block'

.buttons-group
  .btn.btn-info.btn-lg
    = link_to 'Back to index list', profile_hobbies_path( @hobby.profile.id )

JesusParales_hackprofile/app/views/hobbies/index.html.haml
%p#notice= notice
%h1 Hobbies
%table.table
  %thead
    %tr
      %th Name
      %th Description
      %th Preference
      %th Category
      %th{colspan: "3"}
  %tbody
    - @hobbies.each do |hobby|
      %tr
        %td= hobby.name
        %td= hobby.description
        %td= hobby.preference
        %td= hobby.category.name
        /*%td= link_to 'Show', hobby_path( hobby )
        %td= link_to 'Edit', edit_hobby_path( hobby )
        %td= link_to 'Destroy', hobby, method: :delete, data: { confirm: 'Are you sure?' }
%br/

.row.actions
  .btn.btn-info.btn-lg.btn-block
    = link_to 'New Hobby', new_profile_hobby_path(@profile )
  .btn.btn-info
    = link_to 'Back to Edit Page', edit_profile_path(@profile)

JesusParales_hackprofile/app/views/hobbies/new.html.haml
%h1 New Hobby

= form_with(model: [@profile, @hobby], local: true) do |form|
  - if @hobby.errors.any?
    #error_explanation
      %h2
        = pluralize(@hobby.errors.count, "error")
        prohibited this profile from being saved:
      %ul
        - @hobby.errors.full_messages.each do |message|
          %li= message
  .field.form-group
    = form.label :name
    = form.text_field :name, class: 'form-control'
  .field.form-group
    = form.label :description
    = form.text_field :description, class: 'form-control'
  .field.form-group
    = form.label :preference
    = form.select :preference, @preferences, include_blank: true
  .field.form-group
    = form.label :category
    = form.select :category_id, @categories, include_blank: true
  .actions
    = form.submit class: 'btn btn-info btn-lg btn-block'

.buttons-group
  .btn.btn-info
    = link_to 'Back to index list', profile_hobbies_path( @profile )

JesusParales_hackprofile/app/views/hobbies/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @hobby.name

%p
  %strong Description:
  = @hobby.description

%p
  %strong Preference:
  = @hobby.preference

%p
  %strong Category:
  = @hobby.category.name

= link_to 'Edit', edit_hobby_path(@hobby)
|
= link_to 'Back to index list', profile_hobbies_path( @hobby.profile.id )