JesusParales_hackprofile/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'profile/valentinaloreto' => 'profiles#json_response'

  get 'browse', to: 'browse#search', as: :browse  # 1 -renders the search view bar. linked to friends/new

  post 'friends/new', to: 'friends#new'
  post 'friends', to: 'friends#create' #f 3 ----from hidden form
  get '/friends/:id', to: 'friends#show', as: 'friend'

  resources :profiles, only: [:show, :edit, :update], shallow: true do
    resources :hobbies, except: :show
    resources :photos
    resources :certificates, except: :show
  end
end

JesusParales_hackprofile/app/models/certificate.rb
class Certificate < ApplicationRecord
  belongs_to :profile
  has_one_attached :file
end

JesusParales_hackprofile/app/controllers/certificates_controller.rb
class CertificatesController < ApplicationController
  before_action :set_profile, only: [:index, :new, :create]
  before_action :set_certificate, only: [:show, :edit, :update, :destroy]

  def index
    @certificates = Certificate.all
  end

  def new
    @certificate = Certificate.new
  end

  def create
    @certificate = @profile.certificates.build(certificate_params)
    if @certificate.save
      redirect_to profile_certificates_path(@profile), notice: 'certificate was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @certificate.update(certificate_params)
      redirect_to profile_certificates_path(@certificate.profile.id), notice: 'certificate was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @profile = @certificate.profile.id
    @certificate.destroy
    redirect_to profile_certificates_path(@profile), notice: 'certificate was successfully destroyed.'
  end

  private

  def set_certificate
    @certificate = Certificate.find(params[:id])
  end

  def set_profile
    @profile = Profile.find(params[:profile_id])
  end

  def certificate_params
    params.require(:certificate).permit(:name, :file)
  end
end

JesusParales_hackprofile/app/helpers/certificates_helper.rb
module CertificatesHelper
end

JesusParales_hackprofile/app/views/certificates/edit.html.haml
%h1 Editing Certificate

= form_with(model: @certificate, local: true) do |form|
  - if @certificate.errors.any?
    #error_explanation
      %h2
        = pluralize(@certificate.errors.count, "error")
        prohibited this profile from being saved:
      %ul
        - @certificate.errors.full_messages.each do |message|
          %li= message
  .field.form-group
    = form.label :name
    = form.text_field :name, class: 'form-control'
  .field.form-group
    = form.label :file
    = form.file_field :file, class: 'form-control'
  .actions
    = form.submit class: 'btn btn-info btn-lg btn-block'

.buttons-group
  .btn.btn-info.btn-lg
    = link_to 'Back to index list', profile_certificates_path( @certificate.profile.id )

JesusParales_hackprofile/app/views/certificates/index.html.haml
%p#notice= notice
%h1 Certificates
%table.table
  %thead
    %tr
      %th Name
      %th File
      %th{colspan: "3"}
  %tbody
    - @certificates.each do |certificate|
      %tr
        %td= certificate.name
        %td= link_to 'View file', certificate.file
        /%td= link_to 'Show', certificate_path( certificate )
        %td= link_to 'Edit', edit_certificate_path( certificate )
        %td= link_to 'Destroy', certificate, method: :delete, data: { confirm: 'Are you sure?' }
%br/

.row.actions
  .btn.btn-info.btn-lg.btn-block
    = link_to 'New Certificate', new_profile_certificate_path( @profile )
  .btn.btn-info
    = link_to 'Back to Edit Page', edit_profile_path(@profile)

JesusParales_hackprofile/app/views/certificates/new.html.haml
%h1 New Certificate

= form_with(model: [@profile, @certificate], local: true) do |form|
  - if @certificate.errors.any?
    #error_explanation
      %h2
        = pluralize(@certificate.errors.count, "error")
        prohibited this photo from being saved:
      %ul
        - @certificate.errors.full_messages.each do |message|
          %li= message
  .field.form-group
    = form.label :name
    = form.text_field :name, class: 'form-control'
  .field.form-group
    = form.label :file
    = form.file_field :file, class: 'form-control'

  .actions
    = form.submit class: 'btn btn-info btn-lg btn-block'

.buttons-group
  .btn.btn-info.btn-lg
    = link_to 'Back to index list', profile_certificates_path( @profile )